---

- name: Network Getting Started First Playbook
  connection: network_cli
  gather_facts: false
  hosts: all
  tasks:

    - name: Ensure eth1/5 is a trunk port and ensure 2-50 are being tagged (doesn't mean others aren't also being tagged)
      nxos_l2_interface:
        name: Ethernet4/1
        mode: trunk
        trunk_vlans: 2-50

    - name: Ensure these VLANs are not being tagged on the trunk
      nxos_l2_interface:
        name: Ethernet4/1
        mode: trunk
        trunk_vlans: 51-4094
        state: absent
    
    - name: Add interface using aggregate
      nxos_interface:
        aggregate:
        - { name: Ethernet4/2, admin_state: up, mode: layer2 }
        - { name: Ethernet4/7, admin_state: up, mode: layer2 }
        state: present


    - name: Aggregate Configure interfaces for access_vlan with aggregate
      nxos_l2_interface:
        aggregate:
          - { name: "Ethernet4/2", trunk_vlans: 6-30 }
          - { name: "Ethernet4/7", trunk_vlans: 15-20 }
        mode: trunk
        state: absent